//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Resources.Text.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cave.
        /// </summary>
        public static string Cave {
            get {
                return ResourceManager.GetString("Cave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Road.
        /// </summary>
        public static string EasternRoad {
            get {
                return ResourceManager.GetString("EasternRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer Dave&apos;s Field.
        /// </summary>
        public static string FarmerDavesField {
            get {
                return ResourceManager.GetString("FarmerDavesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer Dave&apos;s Home.
        /// </summary>
        public static string FarmerDavesHome {
            get {
                return ResourceManager.GetString("FarmerDavesHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Store.
        /// </summary>
        public static string GeneralStore {
            get {
                return ResourceManager.GetString("GeneralStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbalist&apos;s Garden.
        /// </summary>
        public static string HerbalistsGarden {
            get {
                return ResourceManager.GetString("HerbalistsGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbalist&apos;s Hut.
        /// </summary>
        public static string HerbalistsHut {
            get {
                return ResourceManager.GetString("HerbalistsHut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider Forest.
        /// </summary>
        public static string SpiderForest {
            get {
                return ResourceManager.GetString("SpiderForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sue&apos;s House.
        /// </summary>
        public static string SuesHouse {
            get {
                return ResourceManager.GetString("SuesHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town Square.
        /// </summary>
        public static string TownSquare {
            get {
                return ResourceManager.GetString("TownSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Road.
        /// </summary>
        public static string WesternRoad {
            get {
                return ResourceManager.GetString("WesternRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Garden.
        /// </summary>
        public static string YourGarden {
            get {
                return ResourceManager.GetString("YourGarden", resourceCulture);
            }
        }
    }
}
